transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/datamem.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/outmem.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/inmem.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/instr_rom.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/signed_non_restoring_div.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/non_restoring_div.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/reg_fetch_decode.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/reg_decode_execute.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/reg_execute_memory.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/reg_memory_writeback.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/forward1mux.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/forward2mux.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/rs1d_mux.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/rs2d_mux.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/hazard_unit.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/wb_mux.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/pipeline.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/regfile.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/reg_dec.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/pc_reg.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/op_b_mux.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/op_a_mux.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/lsu.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/immGen.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/ctrl_unit.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/brcomp.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/br_mux.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/alu.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/src/add4.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/vedic_mult_32bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/vedic_mult_16bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/vedic_mult_8bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/vedic_mult_4bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/vedic_mult_2bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/twos_comp_64bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/signed_vedic_mult_32bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/half_adder.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/CLA_32bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/CLA_16bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/CLA_8bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/CLA_4bit.v}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/32-bit-Signed-Vedic-Multiplier-main/32-bit-Signed-Vedic-Multiplier-main/2sComp.v}

vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/../../../../../../Desktop/singlecycle-test/01_bench {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/../../../../../../Desktop/singlecycle-test/01_bench/tbench.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/../../../../../../Desktop/singlecycle-test/01_bench {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/../../../../../../Desktop/singlecycle-test/01_bench/scoreboard.sv}
vlog -sv -work work +incdir+C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/../../../../../../Desktop/singlecycle-test/01_bench {C:/Users/Admin/Downloads/Compressed/pipeline-main/pipeline-main/quartus/pipeline_restored/../../../../../../Desktop/singlecycle-test/01_bench/driver.sv}

vsim -t 1ps -L altera_ver -L lpm_ver -L sgate_ver -L altera_mf_ver -L altera_lnsim_ver -L cycloneii_ver -L rtl_work -L work -voptargs="+acc"  tbench

add wave *
view structure
view signals
run -all
